<?php

namespace Razm;

class RazmnixPhoenixIcon {
	public static array $svgs = [
		'home'             => 'home',
		'instagram'        => 'instagram',
		'moon'             => 'moon',
		'phoenix'          => 'phoenix',
		'telegram'         => 'telegram',
		'twitter'          => 'twitter',
		'mail'             => 'mail',
		'mail2'            => 'mail2',
		'sun'              => 'sun',
		'toman'            => 'toman',
		'youtube'          => 'youtube',
		'bag'              => 'bag',
		'alarm'            => 'alarm',
		'video'            => 'video',
		'wallet'           => 'wallet',
		'walletCircle'     => 'walletCircle',
		'question'         => 'question',
		'mission'          => 'mission',
		'logout'           => 'logout',
		'academy'          => 'academy',
		'academy2'         => 'academy2',
		'academyCircle'    => 'academyCircle',
		'3Circle'          => '3Circle',
		'arrowLeft'        => 'arrowLeft',
		'arrowRight'       => 'arrowRight',
		'arrowSpiral'      => 'arrowSpiral',
		'arrowSpiral2'     => 'arrowSpiral2',
		'chat'             => 'chat',
		'folder'           => 'folder',
		'bookmarks'        => 'bookmarks',
		'watch'            => 'watch',
		'watch2'           => 'watch2',
		'microphone'       => 'microphone',
		'microphoneCircle' => 'microphoneCircle',
		'phone'            => 'phone',
		'phoneCircle'      => 'phoneCircle',
		'edit'             => 'edit',
		'editCircle'       => 'editCircle',
		'editSquare'       => 'editSquare',
		'editSquareCircle' => 'editSquareCircle',
		'eye'              => 'eye',
		'heart'            => 'heart',
		'heart2'           => 'heart2',
		'download'         => 'download',
		'patternCircle'    => 'patternCircle',
		'star'             => 'star',
		'starCircle'       => 'starCircle',
	];
}
